name: Android Test Maestro

on:
  pull_request:
    branches:
      - master
    paths:
      - '.github/workflows/android-test.yml'
      - 'android/**'
      - 'example/android/**'
      - 'fabricexample/android/**'
      - 'maestro-tests/**'
  push:
    branches:
      - master

concurrency:
  group: ${{ github.ref }}-android
  cancel-in-progress: true

jobs:
  android-build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-dependencies

      - name: Install dependencies
        run: |
          brew update
          brew install Caskroom/cask/xquartz
#          brew install android-sdk
#          sdkmanager "system-images;android-30;google_apis;x86_64" "emulator" "platform-tools"
#          sdkmanager --licenses

      - name: Pull dependencies
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: ${{ hashFiles('./package.json') }}

      - name: Cache example node modules
        id: cache-example-npm
        uses: actions/cache@v3
        env:
          cache-name: cached-example-npm-deps
        with:
          path: example/node_modules
          key: ${{ hashFiles('./example/yarn.lock') }}-${{ hashFiles('./yarn.lock') }}

      - name: Install required example dependencies on yarn.lock change
        if: steps.cache-example-npm.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
        working-directory: example

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Build Android
        run: ./gradlew assembleDebug --stacktrace
        working-directory: example/android

      #      - name: Upload APK
      #        uses: actions/upload-artifact@v1
      #        with:
      #          name: apk
      #          path: example/android/app/build/outputs/apk/debug/app-debug.apk

      - name: Start virtual display
        run: |
          sudo Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          export DISPLAY=:99

      - uses: dniHze/maestro-test-action@v1

      - uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          arch: x86_64
          ram-size: 2048M
          target: default
#          disable-animations: false
          emulator-options: -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim
          script: adb install example/android/app/build/outputs/apk/debug/app-debug.apk && adb shell pm list packages com.pagerviewexample && maestro test --format=junit --output=report.xml --no-ansi maestro-tests/test.yaml
#          script: maestro test --format=junit --output=report.xml --no-ansi maestro-tests
